apiVersion: v1
items:
- apiVersion: v1
  stringData:
    glific-bfm-reminder-template-id: <dummy>
    glific-password: <dummy>
    glific-username: <dummy>
    glific-welcome-template-id: <dummy>
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: glific1
      meta.helm.sh/release-namespace: default
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: glific1
    name: glific1
    namespace: default
  type: Opaque
- apiVersion: v1
  stringData:
    analytics-db-url: jdbc:postgresql://<dbhost>:5432/analytics?sslmode=disable
    database: jalsoochaknew
    db-url: jdbc:postgresql://<dbhost>:5432/jalsoochak?sslmode=disable
    host: "192.168.5.170"
    keycloak-admin-client-secret: <dummy>
    keycloak-credential-secret: <dummy>
    keycloak-issuer-uri: https://<domain>/keycloak/realms/jalsoochak-realm
    keycloak-public-key: <dummy>
    keycloak-realm: jalsoochak-realm
    mail-id: <dummy>
    mail-password: <dummy>
    mail-username: <dummy>
    password: <dummy>
    port: "5432"
    username: <dummy>
  kind: Secret
  metadata:
    annotations: {}
    labels:
      k8slens-edit-resource-version: v1
    name: jalsoochak
    namespace: default
  type: Opaque
- apiVersion: v1
  stringData:
    accessKey: <dummy>
    bucket: <dummy>
    endpoint: <dummy>
    region: <dummy>
    root-password: <dummy>
    root-user: <dummy>
    secretKey: Beehyv@123
  kind: Secret
  metadata:
    annotations:
      meta.helm.sh/release-name: minio
      meta.helm.sh/release-namespace: default
    labels:
      app.kubernetes.io/instance: minio
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: minio
      app.kubernetes.io/version: 2024.1.29
      helm.sh/chart: minio-13.3.1
    name: minio
    namespace: default
  type: Opaque
- apiVersion: v1
  kind: Secret
  stringData:
    .dockerconfigjson: |-
        <dockerlogintoken>
  metadata:
    name: ecr-registry
    namespace: default
  type: kubernetes.io/dockerconfigjson
- apiVersion: v1
  stringData:
    admin-password: <dummy>
    database: keycloak
    db-url: jdbc:postgresql://<dbhost>:5432/keycloak?sslmode=disable
    host: "<dbhost>"
    password: <dummy>
    port: "5432"
    username: <dummy>
  kind: Secret
  metadata:
    annotations: {}
    name: keycloak
    namespace: default
  type: Opaque
kind: List
metadata:
  resourceVersion: ''
