# Common Labels
labels:
  app: "message-service"
  group: "core"


ingress:
  enabled: true
  # zuul: true
  context: "api/v1/message"
# # Init Containers Configs

# Container Configs
image:
  repository: "252649026375.dkr.ecr.ap-south-1.amazonaws.com/message-service"
  tag: "58e68dad38c33eb22faa9c82ee5731c27e96af3c"
replicas: "1"
# tracing-enabled: true
# healthChecks:
#   enabled: true
#   livenessProbePath: "/management-service/health"
#   readinessProbePath: "/management-service/health"

# Additional Container Envs
env: |
  - name: NOTIFICATIONS_DRY_RUN
    value: "false"
  - name: JAVA_OPTS
    value: -Xmx192m -Xms192m
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    value: "kafka-kraft-controller-headless:9092"
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      secretKeyRef:
        key: db-url
        name: jalsoochak
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        key: username
        name: jalsoochak
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: jalsoochak
  - name: KEYCLOAK_AUTH_SERVER_URL
    value: "http://keycloak:80/keycloak"
  - name: SPRING_MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        key: mail-username
        name: jalsoochak
  - name: SPRING_MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mail-password
        name: jalsoochak
  - name: MAIL_FROM_EMAIL
    valueFrom:
      secretKeyRef:
        key: mail-id
        name: jalsoochak
  - name: SPRING_MAIL_PROPERTIES_MAIL_SMTP_DEBUG
    value: "true"
  - name: KEYCLOAK_REALM
    valueFrom:
      secretKeyRef:
        key: keycloak-realm
        name: jalsoochak
  - name: KEYCLOAK_PUBLIC_KEY
    valueFrom:
      secretKeyRef:
        key: keycloak-public-key
        name: jalsoochak
  - name: KEYCLOAK_CLIENT_ID
    value: "jalsoochak-app"
  - name: KEYCLOAK_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        key: keycloak-credential-secret
        name: jalsoochak
  - name: KEYCLOAK_ISSUER_URI
    valueFrom:
      secretKeyRef:
        key: keycloak-issuer-uri
        name: jalsoochak
  - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
    value: "http://servicediscovery:8761/eureka"
  - name: GLIFIC_NUDGE_TEMPLATE_ID
    value: "7986"
  - name: GLIFIC_ESCALATION_TEMPLATE_ID
    value: "829817"
  - name: GLIFIC_NUDGE_FLOW_ID
    value: "37300"
  - name: GLIFIC_WELCOME_FLOW_ID
    value: "37684"
  - name: MINIO_ENDPOINT
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: accessKey
        name: minio
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: secretKey
        name: minio
  - name: MINIO_REGION
    valueFrom:
      secretKeyRef:
        key: region
        name: minio
  - name: MINIO_BUCKET
    value: "escalation-reports"
  - name: MINIO_BASE_URL
    valueFrom:
      secretKeyRef:
        key: endpoint
        name: minio
  - name: GLIFIC_API_URL
    value: "https://api.arghyam.glific.com/api"
  - name: GLIFIC_AUTH_URL
    value: "https://api.arghyam.glific.com/api/v1/session"
  - name: GLIFIC_USERNAME
    valueFrom:
      secretKeyRef:
        key: glific-username
        name: glific
  - name: GLIFIC_PASSWORD
    valueFrom:
      secretKeyRef:
        key: glific-password
        name: glific
  - name: GLIFIC_LOGIN_OTP_TEMPLATE_ID
    value: "702101"
  - name: APP_BASE_URL
    value: "https://jalsoochak.beehyv.com"
  - name: MAIL_PROVIDER
    value: "sendgrid"
  - name: MAIL_FROM_NAME
    value: "Jalsoochak"
  - name: MAIL_LOGO_URL
    value: "https://lh3.googleusercontent.com/d/1WUwmfNG_wyWF_G31MaWCtWIsZCxHy5g2"
  - name: SENDGRID_API_KEY
    valueFrom:
      secretKeyRef:
        key: SENDGRID_API_KEY
        name: jalsoochak
  - name: SENDGRID_TEMPLATE_PASSWORD_RESET
    value: "d-9d83de3639254c18b86fa2834f4a5db1"
  - name: SENDGRID_TEMPLATE_REINVITATION
    value: "d-3710ff4d9d874cf1950c589c6f71d752"
  - name: SENDGRID_TEMPLATE_DEFAULT_INVITATION
    value: "d-7721978b67bf4f0083891657ed584447"
  - name: SENDGRID_TEMPLATE_SUPER_USER_INVITATION
    value: "d-6ff964820aae4e03866dd39f64976287"
  - name: SENDGRID_TEMPLATE_STATE_ADMIN_INVITATION
    value: "d-ec98926fa9ed4046b3bf9b85c7a1a7e3"
