name: Reusable Helm Deployment

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name to deploy'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag'
        required: true
        type: string
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string

jobs:
  Helm-Deployment:
    name: Deployment for ${{ inputs.service_name }}
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout DevOps Repo
        uses: actions/checkout@v4
        with:
          repository: arghyam/JalSoochak-Devops
          ref: dev
          fetch-depth: 0
          
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Install Helmfile
        uses: helmfile/helmfile-action@v1.9.0
        with:
          helm-plugins: >
            https://github.com/databus23/helm-diff --verify=false
      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV            
      - name: Helm Deployment
        run: |
          IMAGE="${{ inputs.image_tag }}"
          helmfile apply -f jalsoochak-helmfile.yaml --selector name=${{ inputs.service_name }} --set ${{ inputs.service_name }}.image.tag=$IMAGE
        working-directory: infra/deploy-as-code
